In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all" # to run all arguments and not just the last one

import pandas as pd
pd.set_option("display.max_rows", 1000) # or pd.options.display.max_rows = 1000
pd.set_option("display.max_rows", 20)
pd.set_option("precision", 7)
pd.set_option("large_repr", "truncate")

In [7]:
# reading the mpg data
mpg = pd.read_table("c:/Users/309292/Desktop/mpg.txt", sep = '~')
mpg.describe()

mpg.info()

             displ          year          cyl          cty          hwy
count  234.0000000   234.0000000  234.0000000  234.0000000  234.0000000
mean     3.4717949  2003.5000000    5.8888889   16.8589744   23.4401709
std      1.2919590     4.5096463    1.6115345    4.2559457    5.9546434
min      1.6000000  1999.0000000    4.0000000    9.0000000   12.0000000
25%      2.4000000  1999.0000000    4.0000000   14.0000000   18.0000000
50%      3.3000000  2003.5000000    6.0000000   17.0000000   24.0000000
75%      4.6000000  2008.0000000    8.0000000   19.0000000   27.0000000
max      7.0000000  2008.0000000    8.0000000   35.0000000   44.0000000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 11 columns):
manufacturer    234 non-null object
model           234 non-null object
displ           234 non-null float64
year            234 non-null int64
cyl             234 non-null int64
trans           234 non-null object
drv             234 non-null object
cty             234 non-null int64
hwy             234 non-null int64
fl              234 non-null object
class           234 non-null object
dtypes: float64(1), int64(4), object(6)
memory usage: 14.7+ KB

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
0,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact
1,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact
2,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact
3,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact
4,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact
5,audi,a4,2.8,1999,6,manual(m5),f,18,26,p,compact
6,audi,a4,3.1,2008,6,auto(av),f,18,27,p,compact
7,audi,a4 quattro,1.8,1999,4,manual(m5),4,18,26,p,compact
8,audi,a4 quattro,1.8,1999,4,auto(l5),4,16,25,p,compact
9,audi,a4 quattro,2.0,2008,4,manual(m6),4,20,28,p,compact
...,...,...,...,...,...,...,...,...,...,...,...
224,volkswagen,new beetle,2.0,1999,4,auto(l4),f,19,26,r,subcompact
225,volkswagen,new beetle,2.5,2008,5,manual(m5),f,20,28,r,subcompact
226,volkswagen,new beetle,2.5,2008,5,auto(s6),f,20,29,r,subcompact
227,volkswagen,passat,1.8,1999,4,manual(m5),f,21,29,p,midsize
228,volkswagen,passat,1.8,1999,4,auto(l5),f,18,29,p,midsize
229,volkswagen,passat,2.0,2008,4,auto(s6),f,19,28,p,midsize
230,volkswagen,passat,2.0,2008,4,manual(m6),f,21,29,p,midsize
231,volkswagen,passat,2.8,1999,6,auto(l5),f,16,26,p,midsize
232,volkswagen,passat,2.8,1999,6,manual(m5),f,18,26,p,midsize
233,volkswagen,passat,3.6,2008,6,auto(s6),f,17,26,p,midsize